### ISSUE TITLE
Make the Flush action/button less prominent

### ISSUE THREAD

**Issue by namesty** [dOrgTech/homebase-app#103]

**Comment by ammoon** [comment]
![Flush - Greyed Out](https://user-images.githubusercontent.com/34425043/111137831-7e64cf80-853c-11eb-88aa-ee9ee530f22b.PNG)
![Flush](https://user-images.githubusercontent.com/34425043/111137833-7efd6600-853c-11eb-8880-12c77d64a8f6.PNG)
