### ISSUE TITLE
Add effect upon copying DAO address

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#107]
<img width="390" alt="Screen Shot 2021-03-12 at 9 35 14 PM" src="https://user-images.githubusercontent.com/4146923/111016265-db188c80-837a-11eb-834c-d67b732fd456.png">

Pressing the copy button does not produce visible effect for user to confirm they have copied the address

**Comment by fabiolalombardim** [comment]
<img width="446" alt="issue 154" src="https://user-images.githubusercontent.com/37227394/112544326-25f0c600-8db7-11eb-9c95-b0cc77c9e3a6.png">

<img width="421" alt="issue 154 - 2" src="https://user-images.githubusercontent.com/37227394/112544345-2ab57a00-8db7-11eb-8d8c-4d25e8278d18.png">

Closed in #149
