### ISSUE TITLE
Addresses are not readable

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#110]
Request: Show full addresses and link to tzkt

<img width="524" alt="Screen Shot 2021-03-12 at 9 46 04 PM" src="https://user-images.githubusercontent.com/4146923/111016504-67777f00-837c-11eb-976d-899dbd898919.png">

**Comment by fabiolalombardim** [comment]
<img width="520" alt="issue 110 - 2" src="https://user-images.githubusercontent.com/37227394/112545034-060dd200-8db8-11eb-85e4-102720665610.png">

Closed in #149
