### ISSUE TITLE
Signpost for Quorum Threshold

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#111]
Need tooltip explaining quorum threshold and number of tokens which have voted vs. quorum

<img width="228" alt="Screen Shot 2021-03-12 at 9 48 32 PM" src="https://user-images.githubusercontent.com/4146923/111016569-b8877300-837c-11eb-89bc-aadccd028a01.png">

**Comment by benefacto** [comment]
Need design and copy
