### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#112]
<img width="1039" alt="Screen Shot 2021-03-12 at 9 51 54 PM" src="https://user-images.githubusercontent.com/4146923/111016658-30559d80-837d-11eb-8ba1-c1e048b53161.png">

**Comment by fabiolalombardim** [comment]
Closed in #149

**Comment by fabiolalombardim** [comment]
<img width="709" alt="issue 112" src="https://user-images.githubusercontent.com/37227394/112545608-b24fb880-8db8-11eb-90da-53dc701e9807.png">
