### ISSUE TITLE
link to external docs about treasury and registry daos

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#114]
<img width="806" alt="Screen Shot 2021-03-12 at 10 04 11 PM" src="https://user-images.githubusercontent.com/4146923/111017005-f38aa600-837e-11eb-9efe-e789578abf5c.png">

**Comment by benefacto** [comment]
Need links to external docs

**Comment by benefacto** [comment]
We can leave this open until a team update the README w/ details of each

**Comment by magentaceiba** [comment]
completed with FAQ - https://github.com/dOrgTech/homebase-app/issues/267
