### ISSUE TITLE
show current XTZ balance next to amount when making a proposal

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#115]
Show XTZ (or FA2) in proposal divided by the total balance of the DAO. Currently one has to go back and check the DAO's current balance when specifying an amount

<img width="586" alt="Screen Shot 2021-03-12 at 10 11 36 PM" src="https://user-images.githubusercontent.com/4146923/111017208-f5a13480-837f-11eb-9ce6-61f9ad8b7631.png">

**Comment by ammoon** [comment]
![Balance](https://user-images.githubusercontent.com/34425043/111137074-9f78f080-853b-11eb-9d54-e04e2cfaa1bc.PNG)
