### ISSUE TITLE
Design confusion between Homebase logo at top right and the DAO homebase

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#117]
![image](https://user-images.githubusercontent.com/4146923/111017838-a65d0300-8383-11eb-8c6f-eef8e0b41a75.png)

**Comment by ammoon** [comment]
I'll be changing the icon on the element that takes you to the current DAO's root.

**Comment by ammoon** [comment]
Came up with two options:

![Screen Shot 2021-03-16 at 5 12 51 PM](https://user-images.githubusercontent.com/34425043/111395796-ec171580-867a-11eb-8362-78e1e60a13ea.png)
![Screen Shot 2021-03-16 at 5 12 40 PM](https://user-images.githubusercontent.com/34425043/111395800-ede0d900-867a-11eb-8eee-770021fb5f7b.png)
