### ISSUE TITLE
Consolidate in one bar w/ both Yes and No's

### ISSUE THREAD

**Issue by jacobarluck** [dOrgTech/homebase-app#122]
The current approach can be confusing because it shows two different views of the same data on the page. This can be fixed by consolidating all votes into one bar, similar to how it works on tezos agora (see here for example:  https://www.tezosagora.org/period/38) or on Decred Politeia (https://proposals.decred.org/proposals/020b8b0)

<img width="1083" alt="Screen Shot 2021-03-15 at 3 26 16 AM" src="https://user-images.githubusercontent.com/4146923/111117789-59715c00-853e-11eb-882d-91d4d66aba51.png">

**Comment by ammoon** [comment]
![Screen Shot 2021-03-16 at 7 00 48 PM](https://user-images.githubusercontent.com/34425043/111403301-f8569f00-8689-11eb-89ef-6f4edffa5660.png)
