### ISSUE TITLE
Determine DAO token supply earlier in creation flow

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#124]
When setting up a DAO, a creator must determine quorum thresholds and a required stake / fee (later). However, the supply of the DAO's asset is determined later in the flow, causing a user to have to cross-reference what they put in the stepper for the other values. Can a creator determine the total supply earlier in the flow, prior to the following: 

<img width="739" alt="Screen Shot 2021-03-17 at 2 27 26 PM" src="https://user-images.githubusercontent.com/18144858/111519033-10cbc580-872d-11eb-8481-b91bcfb372f8.png">

**Comment by namesty** [comment]
Also, save total supply value in cache, so that we can show it to the user when he's determining the quorum treshold. Something like:

- Quorum Treshold (Total supply = 50000)
