### ISSUE TITLE
Implement FA2 Transfers on Proposals 

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#128]
Ensure asset selection is available aside from just tez depending on the holdings of the treasury. 

<img width="549" alt="Screen Shot 2021-03-17 at 10 52 25 PM" src="https://user-images.githubusercontent.com/18144858/111566388-73e04b00-8773-11eb-8874-c8ec782767ce.png">

**Comment by namesty** [comment]
This may require some slight design tweaks for FA2 token transfers. As we would require probably an extra field or two if a token other than XTZ is selected
