### ISSUE TITLE
Cover main user flows with tests

### ISSUE THREAD

**Issue by benefacto** [dOrgTech/homebase-app#130]
Possible high-level front end test cases (possibly, mocking out the transactions until #129 is delivered):
- [ ] creating a DAO
- [ ] exploring DAOs: if on testnet, do one or more DAOs load without errors?
- [ ] getting proposal details: if a DAO has proposals, then its proposals should have details
- [ ] create a treasury proposal
- [ ] flush (redeem all proposals)
- [ ] vote for proposal
- [ ] vote against proposal
- [ ] batch proposal
- [ ] add registry item proposal
- [ ] add many registry items proposal
- [ ] modify registry item proposal
- [ ] modify many registry items proposal
- [ ] get treasury/holdings: if values are present, they should have their required properties

**Comment by EightRice** [comment]
same as #281
