### ISSUE TITLE
Rename 'Flush' and gate activity

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#138]
<img width="639" alt="Screen Shot 2021-03-19 at 10 06 29 AM" src="https://user-images.githubusercontent.com/18144858/111792642-d2ecaf80-889a-11eb-87f1-179af438d72b.png">

Can we rename "Flush" to "Execute" and gate anyone from pressing the button unless there's a passed proposal to execute?

**Comment by benefacto** [comment]
May need additional changes to know if a proposal has been flushed or not, according to [this comment](https://github.com/dOrgTech/homebase-app/blob/185db94212b779546e27504aa75edb35500c7b8c/src/modules/explorer/pages/Proposals.tsx#L82)

**Comment by benefacto** [comment]
Logic: check if the length of `proposal_key_list_sort_by_date` is greater than 0, if so there is proposals to flush

**Comment by benefacto** [comment]
#146 is blocking testing of this

**Comment by benefacto** [comment]
Should try to repro again on multiple machines
