### ISSUE TITLE
"View all proposals" leads to DAO list instead of proposals for a specific DAO

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#139]
<img width="417" alt="Screen Shot 2021-03-19 at 10 13 18 AM" src="https://user-images.githubusercontent.com/18144858/111793562-c61c8b80-889b-11eb-8ce4-cf05029b28b2.png">

"View all proposals" button leads to the DAO list

**Comment by benefacto** [comment]
This one needs repro

**Comment by namesty** [comment]
This one got fixed with #149
