### ISSUE TITLE
Percentage issues when voting for or against

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#140]
When voting over the quorum threshold either for or against a proposal, the reflected percentage goes well beyond 100% - which if the 'for' limit hits 100%, that should be it because it's enough to pass something. 

<img width="589" alt="Screen Shot 2021-03-19 at 10 24 20 AM" src="https://user-images.githubusercontent.com/18144858/111795139-4ee7f700-889d-11eb-9595-ca58fb7cf4ac.png">

**Comment by benefacto** [comment]
Need to repro this
