### ISSUE TITLE
No area to put a proposal title in the modal

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#141]
At the moment there's a default and no way to customize a proposal title at the moment. Descriptions is there though and I know the metadata handling is being worked on. 

<img width="561" alt="Screen Shot 2021-03-19 at 10 25 53 AM" src="https://user-images.githubusercontent.com/18144858/111795970-1399f800-889e-11eb-9b36-9c96030f7d6c.png">

**Comment by benefacto** [comment]
Only agora post id is currently supported as metadata, will add the UI fields for this though
