### ISSUE TITLE
Proposal creation failure

### ISSUE THREAD

**Issue by benefacto** [dOrgTech/homebase-app#146]
Steps to reproduce:

1. Create a Registry DAO or use an existing one
2. Make an Add Registry Item proposal
3. Follow the prompts to confirm, example parameters:
```
[ { "destination": "KT1RZFnhC5xCXs9bWQ4tfw8ER7Ch9MeaupNf", "kind": "transaction", "amount": 0, "parameters": { "entrypoint": "propose", "value": { "prim": "Pair", "args": [ { "int": "1" }, { "prim": "Left", "args": [ { "prim": "Pair", "args": [ { "int": "0" }, [ { "prim": "Pair", "args": [ { "bytes": "61736466" }, { "prim": "Some", "args": [ { "bytes": "61647366" } ] } ] } ] ] } ] } ] } } } ]
```
4. Receive proposal failure message, example:
```
[
  {
    "kind": "temporary",
    "id": "proto.008-PtEdo2Zk.michelson_v1.runtime_error",
    "contract_handle": "KT1RZFnhC5xCXs9bWQ4tfw8ER7Ch9MeaupNf"
  },
  {
    "kind": "temporary",
    "id": "proto.008-PtEdo2Zk.michelson_v1.script_rejected",
    "location": 3828,
    "with": {
      "prim": "Pair",
      "args": [
        {
          "string": "FAIL_PROPOSAL_CHECK"
        },
        {
          "prim": "Unit"
        }
      ]
    }
  }
]
```

Possible causes: 

- ~~[upgrade of wallet package](https://github.com/dOrgTech/homebase-app/commit/01503bd3a53494d8dc568977588462fcdeb45283#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27):~~ downgrade had no effect and reverting to a commit before the package upgrades had no effect

Current status: ~investigating~ escalating

**Comment by namesty** [comment]
@benefacto I have been testing locally and have not been able to reproduce this locally. Nonetheless I escalated it to Serokell
