### ISSUE TITLE
Include User Balance in a Specific DAO on the page

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#165]
Let a user know how much of a particular DAO's token they have when accessing the DAO - possibly somewhere either on the proposals area or DAO home. 

![Screen Shot 2021-03-29 at 12 31 40 PM](https://user-images.githubusercontent.com/18144858/112869101-c6cad400-908a-11eb-8d18-95a7a68ee838.png)

**Comment by fabiolalombardim** [comment]
<img width="1440" alt="Captura de pantalla 2021-04-11 a las 17 52 47" src="https://user-images.githubusercontent.com/37227394/114311362-bbe25b80-9aee-11eb-976d-0460e4cc3f1a.png">


As long as there is a connected wallet, the amount of tokens that the user owns in a particular DAO is shown.
