### ISSUE TITLE
BUG: Timer doesn't reset on timer completion

### ISSUE THREAD

**Issue by obstropolos** [dOrgTech/homebase-app#177]
"Time left to vote" remains at 00:00:00 after cycle completion, although the next cycle number is updated. 

<img width="1175" alt="Screen Shot 2021-04-09 at 2 57 09 PM" src="https://user-images.githubusercontent.com/18144858/114228093-e512b880-9943-11eb-9650-af0d376f55db.png">

**Comment by namesty** [comment]
This was fixed by #184. But I will leave it open until we merge `fa2-transfers` branch to develop, so that if another member sees this bug on the staging site, it won't be re-reported

**Comment by namesty** [comment]
Closed by #190
