### ISSUE TITLE
Creation Fail - Try again later

### ISSUE THREAD

**Issue by sebuhbitcoin** [dOrgTech/homebase-app#191]
Hello,

The DAO generation Failed.

It tells me to come back later to try again.

Anything i can look at to help fix this ?

**Comment by sebuhbitcoin** [comment]
Deploying on mainnet now.

It got thru the first 2 contracts now its just sitting there on Deploying.

Please advise?

**Comment by sebuhbitcoin** [comment]
Does this platform require white listing? What do I need to do to be able to use it for my DAO.

**Comment by sebuhbitcoin** [comment]
Deploying Sebuh Baker DAO to the Tezos Network
Deploying registry DAO Contract...

I have been patiently waiting for two months for this platform. I assumed it was going to be open for anyone to be able to deploy a DAO.

**Comment by sebuhbitcoin** [comment]
KT1XAtu9pqFFbnjbppB6JYos8ZxtawwJZfVF

Thats the DAO contract from the second contract origination on mainnet.

**Comment by sebuhbitcoin** [comment]
tz1dXpsNAWLHVYNWSqhrHCHT6wh6L1fKZfo1 -- is my address I wish to deploy the DAO from.

**Comment by namesty** [comment]
Hey! Closing this as we solved this issue, which was a missing confirmation block when using a custom rpc, so the DAO got created but not pinned. But we manually pinned this
