### ISSUE TITLE
Deploying crashing

### ISSUE THREAD

**Issue by TronQuix0te** [dOrgTech/homebase-app#197]
This has happened about 4 or 5 times now where the contract deploys and then crashes. Which also causes me to still lose the Tez that I have submitted.

**Comment by namesty** [comment]
Hey @TronQuix0te ! Thanks for reporting this issue. Could you share your DAO creation parameters and opHashes? In some cases, DAOs are indeed deployed but incorrectly pinned to IPFS. So if the DAO creation was indeed succesful, we may be able to pin your DAO manually, so you would not lose the Tez you spent

**Comment by namesty** [comment]
With #212, we're fixing the most common cause for crashes which is not being connected with a wallet at the moment the origination starts. We are also adding more form validation as sometimes creator fails because of wrong configuration parameters. If problem persists, feel free to reopen

**Comment by Trewaters** [comment]
I am experiencing a similar issue on testnet. Should I create a new issue or is there something I can do to fix my issue. I do see the contracts deployed on the block explorer here ( https://florencenet.tzkt.io/opVMT2DfDJQTNhrAfWcoDuvJAUx3KjjUwANXT2SN3UFXZzSbWun )

Thanks for any help you can provide.
