### ISSUE TITLE
Better Explanation for "Token Address"

### ISSUE THREAD

**Issue by johnnyshankman** [dOrgTech/homebase-app#215]
It's not 100% clear that you have to go deploy a contract on your own to get a `kt1` address before using Homebase, unless there's some other way I'm unaware of. I personally hit that step and instantly wasn't sure what to do.

I'm now trying to learn how Florencenet deploys work so I can get myself some tez from the faucet and then deploy a contract. I think it should be more clear this app does not "Create DAOs" it helps setup an instance of the BaseDAO contract and gives you a UI to interface with it. Or at least thats what it seems like to me.

**Comment by bmann** [comment]
Yep, same stage I'm at.

**Comment by johnnyshankman** [comment]
Would be helpful if it included a link to some documentation. 

`This should be the address of your BaseDAO deployed contract. See: _____`

**Comment by tbbrito** [comment]
Did you manage to make it happen ?

**Comment by johnnyshankman** [comment]
I actually ended up building my DAO on Ethereum Tokens + Snapshot.io and haven't had a moment to come back to this.
