### ISSUE TITLE
NFT Treasury loading Blank Page.

### ISSUE THREAD

**Issue by sebuhbitcoin** [dOrgTech/homebase-app#237]
Hello, the nft page was working. I was able to deposit two nfts. now the page just loads a blank screen and i cannot get to view the nfts.

i am wondering if the indexing is off or something. i am not sure.

here is the page in question.

https://tezos-homebase.io/explorer/dao/KT19CF3KKrvdW77ttFomCuin2k4uAVkryYqh/nft

Sebuh's Baker DAO. 

Thanks for looking into it.

**Comment by sebuhbitcoin** [comment]
[tezos-homebase.io-1638055503140.log](https://github.com/dOrgTech/homebase-app/files/7612536/tezos-homebase.io-1638055503140.log)

here is my console log with some errors.

**Comment by sebuhbitcoin** [comment]
https://objkt.com/profile/KT19CF3KKrvdW77ttFomCuin2k4uAVkryYqh/owned here is the link of the DAO nft treasury on objkt.com.

what i think happened is after i added the "cavedelica" it broke. it was working before i added that one.

**Comment by sebuhbitcoin** [comment]
Update: blank Page is gone now, but only Hicetnunc Minter generated OBJKT NFTS are loading.

objkt.com created nfts, or NFTS generated on independent sites like Sutuverse or pixel panda or Tezotopia are not being displayed.

**Comment by namesty** [comment]
Fixed in #243
