### ISSUE TITLE
Proposal Created but visably Missing after Creation

### ISSUE THREAD

**Issue by sebuhbitcoin** [dOrgTech/homebase-app#238]
I created a new proposal. The transaction went thru smoothly. 

https://tzkt.io/ooWTNZJG5xazsNXCrpPBiUAyRW7mjyZ7gv8UjdnnzwazWM3NLgz

On the DAO interface the proposal is not visible. It looks like there is no Proposals been made yet. This was the first proposal.

Also,  The proposal fee when creating was reported as 100,000 SEB, but the DAO was created with 1000.00 SEB Deposit for Proposals. I believe the decimals is incorrect. SEB Has 2 decimals. 

Proposal in storage viewable on TZKT.io
https://tzkt.io/KT19CF3KKrvdW77ttFomCuin2k4uAVkryYqh/storage/38283

[proposals page console log by sebuh tezos-homebase.io-1638057076334.log](https://github.com/dOrgTech/homebase-app/files/7612557/proposals.page.console.log.by.sebuh.tezos-homebase.io-1638057076334.log)

here is the console log from my brave browser while trying to look at the active proposals page.

**Comment by sebuhbitcoin** [comment]
I have a feeling the issue may have being caused by the Cavedelica Tezotop NFT that was deposited into the treasury, as it has caused an issue with the nft treasury page loading.

**Comment by namesty** [comment]
Fixed in #243
