### ISSUE TITLE
Transfer NFT Proposal on NFT Treasury Page not Generating Transaction Confirmation / Proposal

### ISSUE THREAD

**Issue by sebuhbitcoin** [dOrgTech/homebase-app#239]
I am trying to create a proposal to transfer an NFT from the NFT treasury page. It will not load the transfer.

Here is the Error Log.

and what i see on the screen. 
[proposal form for NFT Transfer error log - brave browser - windows 10.log](https://github.com/dOrgTech/homebase-app/files/7697936/proposal.form.for.NFT.Transfer.error.log.-.brave.browser.-.windows.10.log)
![send button not functioning to generate proposal transaction confirmation](https://user-images.githubusercontent.com/5566620/145695859-1df641b9-3562-4119-b9d5-3721e9bdfd3f.JPG)

`ProposalForm.tsx:134 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'transfers')
    at ProposalForm.tsx:134
    at createFormControl.ts:1008
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)`

**Comment by sebuhbitcoin** [comment]
Ahh it seems I am on "voting on proposals" phase. -- Maybe a better error tooltip would help in this type of situation.

**Comment by namesty** [comment]
Yes, and agreed, added proper tooltips and disabled buttons if not on proposal period in #243
