### ISSUE TITLE
Wallet disconnects if connected from the explorer page or when switching to a different DAO

### ISSUE THREAD

**Issue by ammoon** [dOrgTech/homebase-app#244]
Steps to reproduce:

1. Start from the DAO explorer page
2. Click on "Connect Wallet" to connect your wallet
3. Click on any DAO on the explorer page
4. Wallet is now disconnected

or

1. Start from any DAO
2. Click on "Connect Wallet" to connect your wallet
3. Click on the Homebase logo to return to the DAO explorer page
4. Notice that the wallet is still connected
5. Click on any DAO on the explorer page
6. Wallet is now disconnected

**Comment by CastilloLuis** [comment]
Fixed in #264
