### ISSUE TITLE
Update Creator to V2 UI

### ISSUE THREAD

**Issue by ammoon** [dOrgTech/homebase-app#275]
Current https://tezos-homebase.io is using a deprecated/old version of the DAO Creator (https://tezos-homebase.io/creator/dao). We require to update it to latest designs attached above.

- [x] Select Template
- [x]  Configure DAO settings
- [x] Configure proposal & Voting
- [x] Adjust Quorum, Review Information
- [x] FAQ link (How to... text)
- [x] Stepper (next, previous)

Designs: https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=0%3A1

**Comment by CastilloLuis** [comment]
This will require refactoring components and their layout, I suggest to create small PRs for each part so we don't miss any functionality or break something
