### ISSUE TITLE
Fix Proposal View for Lambda

### ISSUE THREAD

**Issue by Man-Jain** [dOrgTech/homebase-app#326]
**Description (what needs to be done) / Expected Behavior**

Parse the bytes provided by the Indexer into individual fields that make up the definition of the lambda function.

**Acceptance Criteria**

Print out or display the data in human-legible form and have it be the same as what we know we submitted when we created the lambda proposal. 

We can verify the task was successfully done if when we're fetching the info from the Indexer it matches what we sent.

**Supporting information (Figma link, notes, etc)**

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI
To see the lambda UI on that file, go to the top left of the Figma file, click on the Figma icon, and you'll see the Lambda page.

See proposal details box for UI.

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by EightRice** [comment]
parse proposal bytes to get parameters

**Comment by magentaceiba** [comment]
More detailed notes from our discussion:

To find the structure of the Lambda proposal and type that into the application.

Depending on the type of proposal, we branch differently. 

There's a hook that gets the proposal. Log that. - pass the bytes and get the parameters for any proposal that we executed.

Get the data types from the lambda proposal and have a branch of the view for that particular proposal.
And handle that accordingly in the app.
We need the functions to pass this info into the UI.

Can be one of 3 types: treasury proposal, registry proposal, lambda proposal
(currently in the application there is only treasury proposal)
