### ISSUE TITLE
Unstake from ALL proposals

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#358]
When you vote on a proposal, you need to stake a certain amount of DAO tokens towards that vote. Once the lifecycle of that proposal is over, you can unstake those tokens so that you may have them available for withdraw. 

The point of this issue is to allow users to unstake DAO tokens from all proposals at once. This could be achieved by stringing together multiple transactions (like in the DAO creator)

OR

To have the app automatically unstake the tokens once the proposal lifecycle is over. This can be achieved by attaching the unstake actions for all users to the Execute or Drop.

**Comment by magentaceiba** [comment]
note from Alana on a possible UI solution here:
solution option: modal pops up with each one and you can check each... or select all with warning that they might get errors if something happens midway through. or set a max # of unstakable at one time to reduce errors.

**Comment by EightRice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tezos-Homebase-63238426ddf385159a4c4b12/issues/dOrgTech/homebase-app/358?planning-poker) with Zenhub @Man-Jain @fabiolalombardim @thenerdcat

**Comment by Man-Jain** [comment]
@ammoon Can you please create a design for where we should put this `Unstake From Proposals` button? 

![Screenshot 2023-01-21 at 8.41.44 AM.png](https://images.zenhubusercontent.com/6325cd05bc92355981959935/beee4747-6fbd-4cf6-b6ea-7f237762e4a2)

For context, this button does the same work as `Unstake votes` on the Proposal Detail page but this will be a button common for all the Proposals. I was thinking it should be put somewhere on the User Page.

**Comment by ammoon** [comment]
> @ammoon Can you please create a design for where we should put this `Unstake From Proposals` button?
> 
> ![Screenshot 2023-01-21 at 8.41.44 AM.png](https://camo.githubusercontent.com/60390afd31ec75660e5a202063c6836adcf22295ca5ebf94a7c21ea5774729f6/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3633323563643035626339323335353938313935393933352f62656565343734372d366662642d346366362d623665612d376632333737363265346132)
> 
> For context, this button does the same work as `Unstake votes` on the Proposal Detail page but this will be a button common for all the Proposals. I was thinking it should be put somewhere on the User Page.

Yup, here's a screenshot and the link to the Figma

![image](https://user-images.githubusercontent.com/34425043/213852140-ca74fba3-c2f4-432d-a875-6d20acedf373.png)

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=395%3A1&t=I0inp5NTFhhqMsM5-0

**Comment by Man-Jain** [comment]
Testing Scenario - Create two proposals

1. In the first one, vote for yes and then drop the proposal.
2. In the second proposal, vote for yes, vote for no and then drop the proposal
3. Go to User page and then click Unstake Votes button, confirm the transaction and then you should have your token available again.
