### ISSUE TITLE
[Lite] Access levels

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#374]
different access levels result from the two available checkboxes in the _Create_ screen in combination with the boolean value of the _Join_ button pertaining to each DAO and whether or not the wallet is connected:

   **Non-logged in.** 

✔ Can browse and see all the proposals on public DAOs.
❌ Will not see any private DAOs.
❌ Can’t click any Join button (the join button might not even be visible for users that haven’t logged in, but if it is visible, clicking it will simply pull up a modal saying something like  “you can’t join a community without logging in first”)
❌ New Proposal button is not present

   **Logged in but not a member of a DAO.** 

✔  Can browse any public DAOs and see all their proposals
⚡Clicking on Join will trigger a “balmanceOf” call. If they have no DAO tokens in their wallet, we pop a message like “To join <DAO NAME> your balance of <TOKEN SYMBOL> must be more than zero.”
❌ New Proposal button is not present

   **Logged in and a member of a DAO.**

✔  Can browse any public DAOs and see all their proposals
❌ Join button not present.
⚡New Proposal is present and it works.

**Comment by fabiolalombardim** [comment]
If connected:

![Captura de pantalla 2022-12-01 a las 9.25.48.png](https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/0a57af8b-06f3-4f20-ad78-085d795245e2)

If not connected: 

![Captura de pantalla 2022-12-01 a las 9.26.35.png](https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/2bbb4635-2d26-4480-bcf3-5e359b99233c)

Connected and not member of community:

![Captura de pantalla 2022-12-01 a las 9.27.13.png](https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/6ec4b137-0652-4d67-afa9-c8da69133477)

Connected and member of the community:
![Captura de pantalla 2022-12-01 a las 9.27.53.png]
(https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/e79c290f-f9dd-4b65-a170-30863ce3a445)

No DAO token in their wallet when trying to join:

![Captura de pantalla 2022-12-01 a las 9.29.04.png](https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/5654fdad-0f82-4d90-958b-314d6a4f4aac)
