### ISSUE TITLE
[Lite] Voting options must be unique

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#377]

**Comment by EightRice** [comment]
In the proposal creation view, add a validation to ensure that we don't have any repeating strings in the voting options (and display an error if there are repeating strings).

**Comment by fabiolalombardim** [comment]
![Captura de pantalla 2022-12-01 a las 9.17.52.png](https://images.zenhubusercontent.com/6324b3ee997d7418bb303510/e555d733-efb4-4ca2-b57a-a057d86159fb)

Right now, the validation function, trims the strings and check that they're unique. If not, it returns an error.

**Comment by thenerdcat** [comment]
Approved
