### ISSUE TITLE
Remove tabs from proposal modal and keep each modal form in its own page

### ISSUE THREAD

**Issue by ammoon** [dOrgTech/homebase-app#386]
Right now, users get a tabbed modal that includes Treasury, NFT, and Registry proposal forms. This functionality is redundant since any type of proposal can be accessed from almost any "page" within the DAO. Ideally, a modal form should only pop up in its own page.

**Acceptance Criteria**

- [ ] Remove "Assets/Registry" and "Change Delegate" buttons from the initial Proposals page modal.

- [ ] Remove the tabs from the Treasury, Registry, and NFT proposal modals. Only the corresponding page's modal should show up. (This item has its own issue since the designs for it came first: https://app.zenhub.com/workspaces/tezos-homebase-63238426ddf385159a4c4b12/issues/gh/dorgtech/homebase-app/440 )

**Comment by EightRice** [comment]
Latest design https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=395%3A1&t=zDEfmpQlXxgV85mt-0
