### ISSUE TITLE
Integrate Tezos wallet hooks into scaffolding app

### ISSUE THREAD

**Issue by jessebmiller** [dOrgTech/homebase-app#4]

**Comment by cbrzn** [comment]
For reference: 
- https://medium.com/madfish-solutions/how-to-create-a-basic-dapp-on-tezos-with-thanos-wallet-6e7e52306572
- https://github.com/madfish-solutions/counter-dapp
- https://github.com/madfish-solutions/quipuswap-webapp

**Comment by jessebmiller** [comment]
@cbrzn What's left to complete on this?

**Comment by orishim** [comment]
https://github.com/dOrgTech/homebase-app/pull/28
