### ISSUE TITLE
Text change: flush delay duration

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#414]
**Description (what needs to be done) / Expected Behavior**

in last screen of the dao creator, the phrase "flush delay duration" should be changed to "proposal execution delay", to say consistent text as earlier page

**Acceptance Criteria**
text is changed, and it matches the phrase on the dao creator page where the user sets the proposal execution delay

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by fabiolalombardim** [comment]
Fixed on #438
