### ISSUE TITLE
Create DAO config tab - Deadline EOD Friday 1/13/23

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#430]
Displays all settings that have been configured at the creation of the DAO, along with the three buttons that are currently at the top of the Proposals tab.  
The "New" button would only pertain to modifying the parameters of the DAO by consensus.

Please also show what needs to change on the proposals page or other pages, if you want us to remove certain types of proposals from the modals in other pages.

**Comment by ammoon** [comment]
![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/779eb9ea-33d2-4a70-89c2-61b436d49a6b)

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=395%3A1&t=cwDRC8pmRlh5gYdk-0
