### ISSUE TITLE
Add version identifier next to the DAO name

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#432]
Show the version of the DAO (v1, v2, v3) in the Home tab of the DAO details page.

It can be either next to the logo or next to the DAO name (or both).

**Comment by ammoon** [comment]
Figma with many variations

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=5955%3A919&t=HT5SCnQMoBvXLasg-0

The version with the version indicator next to the DAO name only looks better in my opinion

![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/df55f1a7-9c41-4ea4-9e5c-931e0c5e6975)
