### ISSUE TITLE
Remove the UI elements "Creating Proposals" and the tokens (the ones that are side by side) 

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#433]
In the Proposals page, remove the two UI elements where it shows the current cycles and the stuff next to it on the right

Additionally, on the Home page, remove the UI element that says available balance etc.

**Comment by ammoon** [comment]
![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/a6a373c6-2ebd-41db-8f0d-560138a56f87)

![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/3e20d96d-90e5-4c50-906c-b25dd9132fb4)
