### ISSUE TITLE
Single modal views for proposals in treasury, registry, nft

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#435]
**Description (what needs to be done) / Expected Behavior**

On the explorer

Hand off single modal views for proposals in treasury, registry, nft to Fabiola for code changes. Or just a text explanation of which ones to not show on each. I.e. instead of showing all three sets of proposals in the modal for each, show only one to reduce confusion.

**Acceptance Criteria**

Mockup or description of what to change so frontend can execute.

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by ammoon** [comment]
Here's how the modals should look like:
![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/ef737c05-dffc-4ab9-a618-fa1ce640557f)Image
![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/c8816a7d-065b-488a-8d25-057b9b4cede5)Image
![image.png](https://images.zenhubusercontent.com/633c93af40773016c9f8f529/c09121b9-3683-40e9-a432-6a24bf8e7c1c)Image
For the NFT modal,  the preview image of the NFT that shows after an NFT ID is chosen shouldn't expand/be part of the NFT ID text box. It's a separate item.

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=395%3A1&t=zDEfmpQlXxgV85mt-0

**Comment by fabiolalombardim** [comment]
Closed on #448
