### ISSUE TITLE
Remove the top "back" button from DAO creator

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#437]
Starting with the second step we already have a back button at the bottom of the form, and clicking on the Homebase icon will take us back to the main screen, so there's no reason to have the Back at the top. remove this

![image.png](https://images.zenhubusercontent.com/6328919da61b829b013d86fc/25d03b35-1bc9-40d0-adc1-bfe77994f2c0)

**Comment by fabiolalombardim** [comment]
Closed on #438
