### ISSUE TITLE
Remove the tabs from the Treasury, Registry, and NFT proposal modals.

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#440]
**Description (what needs to be done) / Expected Behavior**
In the explorer, remove the tabs from the Treasury, Registry, and NFT proposal modals. Only the corresponding page's modal should show up.

**Acceptance Criteria**
When the user goes to make a proposal on any of the pages, they see only that page's modal

**Supporting information (Figma link, notes, etc)**

Images below. 
Note, for the NFT modal, the preview image of the NFT that shows after an NFT ID is chosen shouldn't expand/be part of the NFT ID text box. It's a separate item.

https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ/Tezos-Homebase---v2-UI?node-id=395%3A1&t=zDEfmpQlXxgV85mt-0

![homebaseexplorer1.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/66c28244-3516-4a98-9305-d1171a70fa72)

![homebaseexplorer2.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/5833acd1-6736-47f5-afc9-3c5715273a08)

![homebaseexplorer3.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/0815c9ac-c30c-40a4-84dc-0fde8ddbb466)

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by Man-Jain** [comment]
https://github.com/dOrgTech/homebase-app/issues/386 - Duplicate

**Comment by fabiolalombardim** [comment]
Closed on #448
