### ISSUE TITLE
Proposal state is stuck

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#460]
User reported this yesterday on Discord:

Hi !

I have created a DAO, and a transfer proposal.
https://tezos-homebase.io/explorer/dao/KT1NabgUFchQJuPssSBqx797xjVsNdC8kq7v/proposal/3e02ec681b702608b697993873edd9a5caf559304c1eecd303bf9c01bc13b5d8

The status of the proposal is : PASSED
It never changes to EXECUTABLE, as we can see here : https://www.youtube.com/watch?v=auFUekD-5iM&t=4s
So, I can not execute the proposal.

The proposal settings, that I set, are :
Voting Period Duration : 10 blocks
Proposal Execution Delay : 21 blocks
Proposal Expiry Threshold : 41 blocks

(the 21 blocks are passed since a while)

**Comment by Man-Jain** [comment]
We've fixed this issue in release 3.3.1 and any new DAO created won't have this problem going forward.
