### ISSUE TITLE
FA1.2 warning banner

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#479]
**Description (what needs to be done) / Expected Behavior**

put up a banner like the one we had before, saying "The Homebase contract can't transfer FA1.2 tokens. Please make sure any and all tokens you send to the DAO treasury are implementing the FA2 standard." 

**Acceptance Criteria**

 it should show up in the same way as  the "experimental" banner we had before. It should be site-wide (because there's no specific section where people go to transfer token into the contract. They just grab the address and do it from their own wallets)

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by Man-Jain** [comment]
Also Added a filter to only show fa2 tokens in the balances list and transfer proposals.

There will be an error when someone tries to input fa1.2 token in the dao creator - FA1.2 not supported

The banner will only show up once not everytime the page loads
