### ISSUE TITLE
Batch registry proposal fails but app says it's successful

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#494]
| Submitted by | Priority | Wallet | DAO url | 
|---|---|---|---|
| andr************ | MEDIUM | Temple (browser extension) | explorer/dao/KT1JpP9MadgnN5Z73bhuJU8uiwpyzSR9urse/proposals |

## Steps to reproduce 
Create a registry proposal and toggle on `batch transfer` to add more than one entries. 

## Expected vs actual behavior: 
The notification on the bottom left says `Registry proposal transaction confirmed` and it's green, indicated that it went through, but the proposal does not show up in the app and you can see on the block explorer that it actually failed. https://ghostnet.tzkt.io/ooPkQe7tScp1EX5JDoB6kF7Foo7Wuyy4dWDeP5Zz9NSnZUUWFsF/10914260

## Logs from browser console or wallet: 

Screenshot: https://drive.google.com/open?id=1h4HPz09_xsNFhAR1zf8eERM7c3t00cyT

**Comment by Man-Jain** [comment]
I tested the scenario but didn't happen to me.
