### ISSUE TITLE
Token deployment frontend

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#497]
Need to create this two extra pages in the DAO creator to include the option to deploy a token:

https://xd.adobe.com/view/61a546b6-c405-41c8-a8a3-793ca84992e7-34f6/screen/2c9a1970-2471-4fc5-89d8-a0b31308e29f?fullscreen

Manank will additionally add the code from FA2 bakery into this PR so we can deploy the feature intact.

**Comment by EightRice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tezos-Homebase-63238426ddf385159a4c4b12/issues/dOrgTech/homebase-app/497?planning-poker) with Zenhub @fabiolalombardim @Man-Jain @EightRice

**Comment by ammoon** [comment]
Can you have the buttons be the same as the buttons else where in the app? I had created button components as "Main Button" and "Small Button." They're on src/modules/common. The button text should be capitalized instead of everything being uppercase. Thanks!
