### ISSUE TITLE
Get all proposals from both Homebase Graph API and Homebase Lite MongoDB 

### ISSUE THREAD

**Issue by Man-Jain** [dOrgTech/homebase-app#521]

**Comment by EightRice** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tezos-Homebase-63238426ddf385159a4c4b12/issues/dOrgTech/homebase-app/521?planning-poker) with Zenhub @EightRice @fabiolalombardim @Man-Jain
