### ISSUE TITLE
Bugs: Token deployer

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#564]
**Description (what needs to be done) / Expected Behavior**

- [x] Bug: validation error persists after entering token address
- [x] ![adddressInputValidation.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/b87ffd4e-96b7-4075-a796-a6e5059982e4)
- [x] you don't need to have an address. If no address is inputted, the entire amount is minted to the address of the user who is logged in
- [x] ![notRequired.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/f2841c08-54ac-4d27-b087-59a6f535a0d4)
- [x] User experience issue: As a person deploying a token for the first time, at first in this screen there is a placeholder that says Token ID, but as soon as I paste the token address, that changes to 0 without a label. As a new user I wouldn't understand what that 0 is. I'd suggest we add labels underneath the fields, since about 10 users over time have asked us before what the token ID is.
- [x] ![tokenIdNeedsLabel.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/a2e90c91-6635-4773-8a44-f4e6dec4291f)
- [x] Token deployer: address fields are too narrow for full address to show. One solution is to show first part of address and ... last part of address.

**Acceptance Criteria**
validation errors listed above are addressed. Labels below entry boxes on token address, ID, FA2. Please check for any further issues in token deployer.

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by fabiolalombardim** [comment]
token ID label: "Homebase will only track your governance token at a certain ID index, which is a parameter specified upon deploying the token contract. Fungible tokens usually have the ID of 0 (zero)."
