### ISSUE TITLE
UI Adjustments on Lite Proposals

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#567]
**Description (what needs to be done) / Expected Behavior**

- [x] Visual bug: On screensizes 1167+ , Choice field is too close to the radio button captions. Seems like these fields should probably be a little wider on this screen size up too. 

- [x] See similar overlap on end date Text

- [x] It would be helpful if labels of the DD HH MM stay underneath the fields. See what that looks like in second image below

- [x] External Link is required field, but I can press create proposal and sign without anything there. Add required message / throw error if nothign there 
- [x] ![liteProposal.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/e9e09c6c-1c30-4e52-848f-1bffec916ccb)![endDate.png](https://images.zenhubusercontent.com/60351f71fd9cc94582561b1f/591ff5ff-06c1-40e6-832c-776fd729f391)

- [ ] 

**Acceptance Criteria**

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by fabiolalombardim** [comment]
The first 3 bugs were fixed on this PR: https://github.com/dOrgTech/homebase-app/pull/536

They aren't merged yet.
