### ISSUE TITLE
End to end QA

### ISSUE THREAD

**Issue by jessebmiller** [dOrgTech/homebase-app#58]
Including test cases and safe clean build automation

as per
https://cdn.discordapp.com/attachments/804689936388325376/808410071112876032/Screen_Shot_2021-02-08_at_12.42.22_PM.png

**Comment by benefacto** [comment]
I will be working on test automation, continuous integration, test cases for the [services](https://github.com/dOrgTech/homebase-app/tree/develop/src/services) folder
