### ISSUE TITLE
Change delegation settings modal

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#636]
Instead of having a separate step to "reclaim voting power", we can keep that option in the modal constantly.

as per wireframes here:

https://xd.adobe.com/view/61a546b6-c405-41c8-a8a3-793ca84992e7-34f6/screen/52ce9474-6a13-42ae-9d65-fbc8d3e9b47f?fullscreen

**Comment by ammoon** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaTRKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--afabdb4d85c00b18ae9b13757c7a719c127e5513/image.png)
