### ISSUE TITLE
homebase-app: Improve app speed

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#658]
**Description (what needs to be done) / Expected Behavior**

First, evaluate what is causing the sluggish behavior.
Once identified, add specifics to this task description of what needs to be changed. 

Then, move the identified problems' calculation and frontend logic to the backend API to optimize speed.

**Acceptance Criteria**

Please check every criteria as its moved to make sure the calculation is still correct.
PR review please check all changed logic to make sure the calculation is still correct and it's passing the tests.

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by benefacto** [comment]
Hey @magentaceiba , I think this task is a bit too vague for me to start on. Do we have any more specific feedback about what in the app is behaving sluggishly? Is it just general navigation or specific actions? Also, where is this feedback coming from: Tezos or end users or dOrg internally?

**Comment by benefacto** [comment]
No recent feedback that suggests this is a problem
