### ISSUE TITLE
Integrate tests

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#702]
**Description (what needs to be done) / Expected Behavior**

Integrate the tests done by the upwork team, so that as we're doing new features and fixes we run them through a testing pipeline.

**Acceptance Criteria**

**Supporting information (Figma link, notes, etc)**

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by benefacto** [comment]
Duplicate of https://github.com/dOrgTech/homebase-app/issues/673
