### ISSUE TITLE
homebase-app: PRI-1 - Can't connect kukai on ghostnet

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#710]
**Description**

User can't connect kukai wallet on ghostnet. Is a request coming from the Kukai team who are trying to integrate with Homebase.

**Acceptance Criteria**

User should be able to connect either Temple or Kukai wallet on Ghostnet and interact with the app. 

**Supporting information (Figma link, notes, etc)**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcd93da954f8cb71747352daa4d1e0d9c1a4d077/Screenshot_20231026_090512.jpg)

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by benefacto** [comment]
Confirmed that connecting via Temple wallet still works

**Comment by benefacto** [comment]
@magentaceiba  I'm unable to reproduce as I was able to successfully connect via a newly created Kukai wallet (see below). Note: there is a delay of several seconds before the permission prompt within Kukai appears. Is it possible to confirm with the Kukai team that this is no longer an issue?
<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fe2be230bc07dea2942993a9dc7a2ae3e9da098/image.png" alt="image.png" />
<img width="1568" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d79c32683c07370e596e8393294cbb35a86795db/image.png" alt="image.png" />
<img width="1434" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenlOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a0aa5656bd0f559e9d528c3477d816b2da7229c/image.png" alt="image.png" />
