### ISSUE TITLE
Change from table to cards - transactions section on user page

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#725]
**Description (what needs to be done) / Expected Behavior**
See mockups for changes

**Acceptance Criteria**

**Supporting information (Figma link, notes, etc)**

Mockups
https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ?type=design%27&node-id=8248:3127

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by fabiolalombardim** [comment]
Fix in a PR that got merged. The change is up in prod
