### ISSUE TITLE
[LITE] Misaligned component

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#733]

**Comment by EightRice** [comment]
<img width="1010" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjl6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6da59d99c74ca2a9d75cdd47e1e5cf50513a010/image.png" alt="image.png" />

**Comment by csoreff** [comment]
<img width="1152" alt="image" src="https://github.com/dOrgTech/homebase-app/assets/6821977/cdd0d9dc-7b07-4b0f-bc12-acf795a1fda1">
