### ISSUE TITLE
Implement designs for new proposal list and user page layout - Add missing filters and final touches

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#739]
**Description (what needs to be done) / Expected Behavior**
Update the designs linked below for Proposal List and User Page Layout

**Acceptance Criteria**
New designs are implemented and all functionality is still working as expected.

**Supporting information (Figma link, notes, etc)**

Proposal List Re-Design
https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ?type=design%27&node-id=6573:1587

User page layout re-design
https://www.figma.com/file/gXLZPoh1BchigOB5y9YkQZ?type=design%27&node-id=8087:6063

Pending from Alana (eta week of 12/22)
- Nav bar redesign
- Filters design

**When finished, please add Link to the PR or completed Figma / design asset, as a comment to the ticket.**

**Comment by fabiolalombardim** [comment]
Fix in a PR that got merged. The change is up in prod
