### ISSUE TITLE
Correct quorum logic on fixed setting

### ISSUE THREAD

**Issue by magentaceiba** [dOrgTech/homebase-app#758]
Correct quorum logic on fixed setting. Check contract logic going in and also what shows on the frontend in the confirmation screen.

This error might be only the case where the user does not change the default setting of fixed quorum.

The formula should be as shown below. minus one on minimum quroum threshold, and plus one on maximum quorum threshold. So for example, the 2% fixed quorum default should be initial quorum threshold 2, minimum quorum threshold 1, maximum quorum threshold 3.

0(1) below means, If the contract allows 0, set it to 0, if it doesn't, we should set it to 1.

Logic:
If the user inputs value = 25

We set it on the backend like so:
initial_quorum_threshold=25
initial_quorum_change=0 (1)
minimum_quorum_threshold=24
maximum_quorum_threshold=26
max_quorum_change=0(1)

The bug:
Here in this screenshot the user had selected fixed quorum of 2% (or whatever the default was), and these values are incorrect as shown in the DAO settings:

<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkxQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b21a27a18ad6d00b8be9379f9a9c426f60b8447/image.png" alt="image.png" />

**Comment by fabiolalombardim** [comment]
Setting a Fixed Quorum of 40%:

<img width="1461" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2dSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13fbd65061d0f221ae75a590d31cb0d4ceeb2071/Captura%20de%20pantalla%202024-01-30%20a%20las%2018.27.58.png" alt="Captura de pantalla 2024-01-30 a las 18.27.58.png" />

**Comment by fabiolalombardim** [comment]
merged a while a go, and now it's working in prod
