### ISSUE TITLE
XTZ-weighted offchain poll - BACKEND

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#763]
**The task is to allow users to vote on an offchain poll with their XTZ balance instead of the designated governance token of the DAO.** 

When creating a new offchain poll, we store another bool `isXTZ` that defaults to `false` unless the user explicitely sets it to `true.`  

If `isXTZ` is `true` for any given poll, everything else remains the same, but for the vote action, the app queries a different endpoint on tzkt.io that returns the user's XTZ balance instead of the balance of the governance token. 

This task also involves a bit of research to figure out what endpoint to call on tzkt in order to get back the XTZ balance of the user.

**Comment by fabiolalombardim** [comment]
solution was merged
