### ISSUE TITLE
XTZ-weighted offchain poll - FRONTEND

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#764]
When creating a new offchain poll, there is a toggle that allows the author of the poll to set it as XTZ-weighted. If enabled, the app will display XTZ everywhere in the poll instead of the symbol of the governance token. 

**In the explainer text under the switch, replace GVT with the actual symbol of the DAO's governance token.**

<img width="756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88167ac5dbd937d5cf42557d80e1c080350f3c98/image.png" alt="image.png" />

**Comment by fabiolalombardim** [comment]
solution was merged
