### ISSUE TITLE
"back to community" button should point to the DAO page

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#856]

**Comment by EightRice** [comment]
Right now, the button works like a browser `back` button, and if the user goes to the proposal directly using the deep url, it doesn't direct to the main DAO page.

<img width="662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFo4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5bb6f8cc7aeff8b173118ba974a591dabce7b7a/image.png" alt="image.png" />

**Comment by ashutoshpw** [comment]
![image](https://github.com/dOrgTech/homebase-app/assets/7466924/1ce29d26-8ad7-4353-aaa2-a7c1acfcd4a8)

**Comment by ashutoshpw** [comment]
@EightRice There is no "back to community" button on on-chain proposals. Should I add it over there?
