### ISSUE TITLE
Restore "Drop proposal" button

### ISSUE THREAD

**Issue by EightRice** [dOrgTech/homebase-app#859]
The contract allows the author of a proposal as well as the Guardian to end the life cycle of any proposal. In the new UI this button is gone and we should bring it back. 

Here it is in the old version, on the page of the proposal: https://deploy-preview-587--tezos-homebase.netlify.app/explorer/dao/KT1VG3ynsnyxFGzw9mdBwYnyZAF8HZvqnNkw/proposal/21a6cdda548de59ef7fcd9405e12e2d7be78669bcff319ec80741446f06bd405

The functionality should be in the code base around this time frame: https://github.com/dOrgTech/homebase-app/pull/587/commits/3617cbe4ed6c5159d18dd56dcfa7f864f51606fc

**Comment by ashutoshpw** [comment]
Resolved in https://github.com/dOrgTech/homebase-app/pull/860
