### ISSUE TITLE
Locked tokens's token holders modal displays wrong bar color

### ISSUE THREAD

**Issue by namesty** [dOrgTech/homebase-app#95]
![tezos5](https://user-images.githubusercontent.com/36479614/110652854-09506d80-81bd-11eb-91e2-a47f0b935e5e.png)

The green portion of the bar represents the amount of tokens locked vs total tokens. However, the missing portion should be gray, not red.

**Comment by fabiolalombardim** [comment]
<img width="1079" alt="issue 95" src="https://user-images.githubusercontent.com/37227394/112543280-d2ca4380-8db5-11eb-8c88-525885518098.png">

Closed in #149
