### ISSUE TITLE
Create a splash page

### ISSUE THREAD

**Issue by namesty** [dOrgTech/homebase-app#97]
It'd be nice to have a splash page with buttons to link the user to the app, and to the documents/code and a brief explanation of what Homebase is and what it does. Similar to: https://sushi.com/

**Comment by ammoon** [comment]
![Splash 1](https://user-images.githubusercontent.com/34425043/111138177-dac7ef00-853c-11eb-8fc0-7a7af2215e28.PNG)
![Splash 2](https://user-images.githubusercontent.com/34425043/111138179-db608580-853c-11eb-8f53-74334ac83e99.PNG)
